# Generated by Django 5.0.6 on 2024-06-01 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
