# Generated by Django 5.0.6 on 2024-06-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_teammember_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.participant'),
        ),
    ]
