# Generated by Django 5.0.6 on 2024-06-01 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_teammember_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.AddField(
            model_name='teammember',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.participant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.team'),
        ),
    ]
